export const RETRIEVE_AUTH_TOKEN_SUCCESS = 'RETRIEVE_AUTH_TOKEN_SUCCESS';
export const RETRIEVE_AUTH_TOKEN_FAIL = 'RETRIEVE_AUTH_TOKEN_FAIL';

export const FETCH_IMAGE_DATA_SUCCESS = 'FETCH_IMAGE_DATA_SUCCESS';
export const FETCH_IMAGE_DATA_FAIL = 'FETCH_IMAGE_DATA_FAIL';
